{
 "title": "OpenTelemetry HTTP Metrics - Exponential Histogram Example",
 "description": "request rate, error rate, duration",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Exponential Histogram Example"
   }
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "histogram_count(sum(rate(http_server_duration_milliseconds{job=\"$job\", instance=\"$instance\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "histogram_count(sum(rate(http_server_duration_milliseconds{job=\"$job\", instance=\"$instance\", http_status_code=~\"5..\"}[5m]))) / histogram_count(sum(rate(http_server_duration_milliseconds{job=\"$job\", instance=\"$instance\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds{job=\"$job\", instance=\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Duration percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds{job=\"$job\", instance=\"$instance\"}[5m])))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_duration_milliseconds{job=\"$job\", instance=\"$instance\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  }
 ]
}