receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: http://localhost:9090/api/v1/write
    add_metric_suffixes: true
  otlphttp:
    endpoint: http://localhost:4418
  loki:
    endpoint: http://localhost:3100/loki/api/v1/push
  logging/metrics:
    verbosity: detailed
  logging/traces:
    verbosity: detailed
  logging/logs:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
      #exporters: [otlphttp,logging/traces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
      #exporters: [prometheusremotewrite,logging/metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
      #exporters: [loki,logging/logs]
